### ISSUE TITLE
Add HW Acceleration Support

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR_plugin_stream_ffmpeg#7]
Hi,

To help offload transcoding, from CPU to GPU - enable / add in support for HW acceleration? For example, hevc_nvenc codec support?

Thanks!

**Comment by deathbybandaid** [comment]
I've considered this in the past, worth looking at again

**Comment by arrmo** [comment]
Thanks! I can help with the codecs - have been using them in my Plex Postprocessing script. It does help to offload => make use of the encoders (and decoders if desired) in the GPU.

**Comment by arrmo** [comment]
Just a thought, but ... to the code (example pulled),
```
        elif stream_args["transcode_quality"] == "internet720":
            ffmpeg_command.extend([
                                    "-c", "copy",
                                    "-s", "1280X720",
                                    "-b:v", "1000k",
                                    "-b:a", "196k",
                                    "-f", "mpegts"
                                    ])
```

Add a `transcode_quality` of `custom` (perhaps) ... and then have options the parameters (replacing `-c` with `-c:v` and `-c:a`?) ... and just set the parameters based on those options? That would mean just one added transcode quality, agreed? Perhaps also allow for hwaccel (HW based decoding)?

Thanks!

**Comment by deathbybandaid** [comment]
Probably a `def hardware_transcode` if the configuration is set for that.

Maybe allow amd/intel/nvidia


Also should see if a similar methodology works with cvlc for the vlc plugin

**Comment by arrmo** [comment]
Sorry, you lost me there - but likely me. Thinking that there are several, even for just nvidia (e.g. hevc_nvenc, h264_nvenc). So was thinking to put it in config.ini ... no?

Thanks!

**Comment by deathbybandaid** [comment]
Correct, just making sure we do not limit the potential for different hardware.

I also was saying the vlc stream plugin could also probably do gpu transcoding.

There's also the webwatch plugin that uses ffmpeg

**Comment by arrmo** [comment]
That makes sense, agreed! Do they all pull transcoding information from the same place?

**Comment by arrmo** [comment]
OK, trying to add this - seeing if it helps with the logging (and lagging) issue. I added a new (HW) transcoding profile,
```
        elif stream_args["transcode_quality"] == "nvenc720":
            ffmpeg_command.extend([
                                    "-hwaccel", "cuda",
                                    "-c:v", "hevc_nvenc",
                                    "-s", "hd720",
                                    "-c:a", "copy",
                                    "-f", "mpegts"
                                    ])
```

But, when I try to get it to be used, I get the error,
```
[2022-02-24 17:07:39,103] INFO - 192.168.2.64 - - [2022-02-24 17:07:39] "GET /api/tuners?method=stream&channel=65089df3-ff53-45b4-8656-9a0844d4edd8&origin=ceton HTTP/1.1" 500 161 0.017849
Traceback (most recent call last):
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/ProgSSD/fHDHR/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/ProgSSD/fHDHR/fHDHR_web/api/tuners.py", line 20, in __call__
    return self.get(*args)
  File "/mnt/ProgSSD/fHDHR/fHDHR_web/api/tuners.py", line 32, in get
    stream_obj, stream_args, response_dict = streammanager.setup_stream(request, session)
  File "/mnt/ProgSSD/fHDHR/fHDHR/streammanager/__init__.py", line 90, in setup_stream
    streaming_args, response_dict = self.parse_stream_args(request, chan_obj.origin)
  File "/mnt/ProgSSD/fHDHR/fHDHR/streammanager/__init__.py", line 146, in parse_stream_args
    valid_transcode_types = [None, "heavy", "mobile", "internet720", "internet480", "internet360", "internet240"]
  File "/snap/pycharm-community/267/plugins/python-ce/helpers/pydev/_pydevd_frame_eval/pydevd_frame_tracing.py", line 55, in _pydev_stop_at_break
    if t.additional_info.is_tracing:
AttributeError: '_DummyThread' object has no attribute 'additional_info'
2022-02-24T23:07:39Z {'REMOTE_ADDR': '192.168.2.64', 'REMOTE_PORT': '58178', 'HTTP_HOST': 'linuxserver.rkmorris.home:5006', (hidden keys: 20)} failed with AttributeError
```

FYI, I did update,
```
        valid_transcode_types = [None, "heavy", "mobile", "internet720", "internet480", "internet360", "internet240", "nvenc720"]
```

But it may be that I'm putting this in the wrong place in config.ini (I admit, not sure where to find what sections items go in - but that may be me!). I have tried adding the row below to `[ffmpeg]`, also `[streaming]` ... but perhaps the wrong place(s)?
```
transcode_quality = nvenc720
```

Thanks!

**Comment by arrmo** [comment]
OK, not having much luck with HEVC and mpegts - still need to dig. But I do have HW encoding for h.264 running 😄. For now, hard coded `transcode_quality` - will figure out where to put that in config.ini.

Thanks!

**Comment by deathbybandaid** [comment]
I don't think it should be a try so profile of it's own, but rather a config to enable gpu, and possibly support Vaapi as well

**Comment by arrmo** [comment]
Sorry, I meant - I hard coded that value for  now ... trying to figure out which section to add it to in config.ini 🤣

**Comment by deathbybandaid** [comment]
Streaming

**Comment by arrmo** [comment]
That makes sense, tried it there - errored out. Let me take a look again. Thanks!

**Comment by deathbybandaid** [comment]
Oh, I just realized this was for the ffmpeg repo

I'll take a look when I'm at a bigger screen. Should make a new config  for an ffmpeg section

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_stream_ffmpeg/blob/main/ffmpeg_conf.json

**Comment by arrmo** [comment]
No worries! For now, hard-coded it ... just to test. It is working with a forced value (to get the HW transcode happening), but will update the json yet as you note.

Thanks!

**Comment by arrmo** [comment]
OK, I have figured out how to take stdin in to ffmpeg, HW accelerated decoding, then HW accelerated encoding, back out to stdout. Works from the command line just fine (and then to vlc), it's only parameters for the coding that have to be set correctly. It's working for h264, also hevc.

But ... a bit confused I admit on how to configure this => thinking that ffmpeg still needs to be "in the middle", be it rtp or direct input, agreed? Just not sure how to do that. Right now, direct bypasses ffmpeg, right? And ffmpeg forces rtp. Or this this all part of the plugin, and fHDHR always uses ffmpeg in between in any case?

Sorry, trying to wrap my head around the flow. Thanks!

**Comment by deathbybandaid** [comment]
The idea for direct was not to need ffmpeg or cvlc as external depedencies.

That's why those are plugins

**Comment by arrmo** [comment]
Agreed! But I'm thinking direct (or rtp) is the input method from the Ceton - the stream to Plex (or VLC, etc.) ... that's independent, and could be ffmpeg, no? Thinking out loud, but with HW accel in particular, this allows much lower BW to be sent to the client - better for the network, right?

Right now, ffmpeg (output?) is tied to rtp ... but does it need to be? Again, I may be misunderstanding.

Thanks!

**Comment by arrmo** [comment]
And BTW, I have 2 tuners running here right now, in parallel,
1. direct, device straight to ffmpeg, then to vlc (all in bash + vlc GUI). 2 dropped frames in ~ 210k
2. direct, through fHDHR, debug logging on. 120 dropped frames in 45k

**Comment by arrmo** [comment]
Hi,

Coming back to this one - almost have the updates to the plugin working, detecting and running direct and rtp both (and noting if another client has control of a tuner). But ... I'm a bit confused why rtp and ffmpeg are "tied" together => from the Ceton tuner, either direct or rtp should be possible, and with either one ... ffmpeg or not, right?

Thanks!

**Comment by arrmo** [comment]
Hi,

Been digging in to this one as well - and I have a bit of a "crazy" thought. I'm realizing that I can play with parameters almost forever ... and really, I can see a lot of permutations and combinations of desired transcoding options. Heck, for example, I looked at what Plex was running yesterday,
```
/usr/lib/plexmediaserver/Plex Transcoder -codec:0 h264 -hwaccel:0 nvdec -hwaccel_fallback_threshold:0 10 -threads:0 1 -hwaccel_device:0 cuda -live_start_index 0 -probesize 20000000 -i http://127.0.0.1:32400/livetv/sessions/8e778f81-4a14-4946-82b7-9a656fd7b020/5e48950257edcdc2aafe7c88a09124d3/index.m3u8?offset=2.802800&X-Plex-Incomplete-Segments=1&X-Plex-Token=5D1zFrBXXFpvWzhcEdiv -filter_complex [0:0]scale=w=1280:h=720:force_divisible_by=4[0];[0]format=pix_fmts=yuv420p|nv12[1] -map [1] -codec:0 libx264 -crf:0 23 -maxrate:0 3285k -bufsize:0 6570k -r:0 59.939999999999998 -preset:0 veryfast -level:0 4.1 -x264opts:0 subme=1:me_range=4:rc_lookahead=10:me=hex:8x8dct=0:partitions=none -force_key_frames:0 expr:gte(t,n_forced*1) -map 0:1 -metadata:s:1 language=eng -codec:1 copy -copypriorss:1 0 -segment_format mpegts -f ssegment -individual_header_trailer 0 -segment_time 1 -segment_start_number 0 -segment_copyts 1 -segment_time_delta 0.25 -segment_list http://127.0.0.1:32400/video/:/transcode/session/7341cfdf-f566-4925-8c08-5f228f4b2d0d-1/6c6e29d7-4930-4cf8-8d20-dda858b4ff32/manifest?X-Plex-Http-Pipeline=infinite -segment_list_type csv -segment_list_size 5 -segment_list_separate_stream_times 1 -segment_list_unfinished 1 -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 media-%05d.ts -start_at_zero -copyts -vsync cfr -init_hw_device cuda=cuda: -filter_hw_device cuda -y -nostats -loglevel quiet -loglevel_plex error -xioerror -progressurl http://127.0.0.1:32400/video/:/transcode/session/7341cfdf-f566-4925-8c08-5f228f4b2d0d-1/6c6e29d7-4930-4cf8-8d20-dda858b4ff32/progress
```

Wow!  And even my bit of fiddling, I have been changing codec, resolution, bit rate, etc. Too many options 😜. 

So, my crazy thought - just add one more `transcode_quality` to ffmpeg => read from file. Thinking the values are stored in a JSON file, pre-defined file name (transcode.json?) ... but if the quality is set to "file" (for example), go get the information from that file. Then the fHDHR (and plugin) code don't change, while twiddling transcoding (and HW) options forever. Thoughts?

One more on this as well. With ffmpeg, if you want to use HW acceleration for decoding, that's an input file option, so it needs to be specified before `-i`. More info [here](https://ffmpeg.org/ffmpeg.html#Synopsis), and you can see it with their command line,
```
ffmpeg [global_options] {[input_file_options] -i input_url} ... {[output_file_options] output_url} ...
```

So perhaps in the JSON file, have two items as input ... `input_file_options` and `output_file_options`? And use these to "build" the ffmpeg command? `input_file_options` comes before the `-i`, `output_file_options` comes after (the latter just goes where it is now).

Thoughts?

Thanks!

**Comment by arrmo** [comment]
A bit more (crazy) thought on this - again, thinking out loud 😜. I can see from the ffmpeg command line, there are three "sections" ... `[global_options]`, `[input_file_options]` and `[output_file_options]`. All of these would be nice to "customize" => url's are handled automatically, don't mess with those.

What if these options were "sections" in json file? There could be a default file, but if when ffmpeg is called it reads the json, and adds to or replaces the default options with what is in the file. One real nice upside as well ... it could be modified on the fly, trying / playing with codec (and tuning), without having to restart fHDHR (as they are run whenever ffmpeg is about to start, to build the command line). I don't think the changes are substantial, the command building as you have it works well, just a slight extension to it.

And it could be that all the transcode "cases" are in the json file - the ones you already have, and just one more added, named (for example), "custom". Thoughts? Trying to be able to mess with / fine tune this, and without restarting fHDHR would be awesome.

One other possibility. Within a "case", there could be a few configurations => loop through those "sub-cases", stepping to the next one if ffmpeg fails. For two reasons ...
1. I do see that sometimes if the source coding changes / is screwy, transcoding (ffmpeg) can fail
2. It is possible to run out of HW engines => fall back to SW. This is possible with a set of sub-cases. I found [this ](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new)quite surprising ... only 3 engines, even for recent high end Nvidia GPU's?!?!

If this seems reasonable to you, I can try to code up a PR, let you take a look - that may also help to explain it. But do let me know your thoughts.

Thanks!

**Comment by deathbybandaid** [comment]
Seems like a very backburner project tbh

**Comment by arrmo** [comment]
Sort of ... LOL! But I admit, to me it's a bit more "key" ... only because I really need to transcode my recordings before storing them => or I run out of disk space quite quickly, at ~ 18 Mbps that is coming in. Currently I run a post processing script in Plex, converting all recordings after they are done. But for a 4-5 hour sporting event, it can be 2+ hours before it's ready (and can be watched) => I'd rather transcode on the fly - reduce BW (fHDHR to Plex / client), and have the output basically ready immediately. Sort of make sense? 😜 

In any case, I can absolutely see that you are busy, lots of coding going on. I'm more than happy to take this one on - if you don't mind. 100% your call. Not wanting to step on any toes, but trying to help out if I can. Just let me know. Whatever you prefer is OK with me.

Thanks!

**Comment by deathbybandaid** [comment]
Personally I use tdarr to maintain all plex content in hevc.

I then use cloudbox/autoscan with sonarr/radarr/tdarr to inform plex that files have been changed

**Comment by deathbybandaid** [comment]
Basically, using the hdhr plugin, plex and other client expect content to be served in mpegts chunks

**Comment by arrmo** [comment]
Yep, that doesn't change - transcoded I still output mpegts ... just at 2 Mbps, vs. about 10x that 😄

Actually, I think I tried MKV also when I was playing with it, I think Plex was happy - but I admit, I tried a lot of options, can't recall now. OK, just checked, MKV should also work, but no biggie.
https://support.plex.tv/articles/203824396-what-media-formats-are-supported/

**Comment by deathbybandaid** [comment]
Firstly, that list applies to file playback, not streaming.

Secondly, plex Pre-analyzes files for their codec/container. If you change a files audio track from ac3 to aac, plex will fail playback since it has unexpected format. Plex has to re-analyze files when they change.

fHDHR tells plex the mimetype of the content that will be sent.

https://github.com/fHDHR/fHDHR/blob/main/fHDHR_web/api/tuners.py#L52

Also, there is likely hardcoded stuff in Plex's codebase for expectations of a HDHomeRun, which the HDHR plugin lies to Plex about what fHDHR is. Producing expected content is important.

**Comment by arrmo** [comment]
That makes sense, agreed (playback, not streaming). And also 100% agree, Plex is fussy - it needs the correct input. I admit, all I want to try to do is reduce the bit rate, file size 😆. Not change anything outside of that - it's all working, no reason (or desire) to mess with it. But if you don't want the HW transcode, not really an item that helps you out - understand, no issue here.

Thanks.

**Comment by deathbybandaid** [comment]
I think hardware transcode would be valuable for other future interface plugins, but I'd envision the ffmpeg plugin having non-configurable profiles

**Comment by arrmo** [comment]
Sorry, I may be missing the point - but do you mean ... include the transcoding inside the ceton plug in? I guess it could be, no argument here - just thinking that ffmpeg is already set up for transcoding profiles, adding the HW one isn't that substantial of a change. But again, I may be missing your point.

**Comment by deathbybandaid** [comment]
This thread is in the ffmpeg repo. So I picture it in the ffmpeg plugin.

**Comment by arrmo** [comment]
Yes, that makes sense. If you're OK with it, let me take the first (baby) step ... just adding one transcoding provide, for HW encoding. I'll post that here, so you can take a look. Work for you?

Thanks!

**Comment by deathbybandaid** [comment]
Sure

If it's not a route I want to go, it's not hard to maintain an unofficial plugin

**Comment by arrmo** [comment]
100% agreed - you have a great project here, not trying to mess it up by any means!

Thanks.

**Comment by arrmo** [comment]
OK, the baby step, to add in HW transcoding. 2 changes,
1. just allow a new one on the list. I named it "custom" (could be whatever, but didn't want to tie it to what may be in there, as it may change yet)
```
diff --git a/fHDHR/streammanager/__init__.py b/fHDHR/streammanager/__init__.py
index db91776..70db402 100644
--- a/fHDHR/streammanager/__init__.py
+++ b/fHDHR/streammanager/__init__.py
@@ -172,7 +172,7 @@ class StreamManager():
             transcode_quality = self.fhdhr.origins.get_origin_property(origin_name, "transcode_quality")
             self.fhdhr.logger.debug("Client did not select a transcode quality. Defaulting to origin %s setting of %s" % (origin_name, transcode_quality))

-        valid_transcode_types = [None, "heavy", "mobile", "internet720", "internet480", "internet360", "internet240"]
+        valid_transcode_types = [None, "heavy", "mobile", "internet720", "internet480", "internet360", "internet240", "custom"]
         if transcode_quality not in valid_transcode_types:
             response_dict = {"message": "Not Found", "status_code": 503, "headers": "802 - Unknown Transcode Profile"}
             return {}, response_dict
```
2. And, add that codec setup. FYI, it is streaming right now, ~ 15% (3/18) of the original rate.
```
diff --git a/__init__.py b/__init__.py
index be712c3..8fa693a 100644
--- a/__init__.py
+++ b/__init__.py
@@ -212,4 +212,15 @@ class Plugin_OBJ():
                                     "-f", "mpegts"
                                     ])

+        elif stream_args["transcode_quality"] == "custom":
+            ffmpeg_command.extend([
+                                    "-c:v", "hevc_nvenc",
+                                    "-s", "hd1080",
+                                    "-preset", "p6",
+                                    "-tune", "hq",
+                                    "-b:v", "3M",
+                                    "-c:a", "copy",
+                                    "-f", "mpegts"
+                                    ])
+
         return ffmpeg_command
```

That's the extent of the change to at least get basic HW accel in place. I think 🤣.

My thought about the json file, was to let those extend parameters come from a file, that's all => like the (very long) Plex transcoder example above, you can tweak the setup, and then it would just come from a JSON file. Not a biggie, just figured then the code could be "static", even if the codec changed. But that isn't needed to add basic HW encoding, like above.

By all means - tear it up!

**Comment by arrmo** [comment]
BTW, as I'm still learning here (very much so!) ... the codecs above the one I added - that include `-c copy`, but also `-s` and a new size ... does that work? I thought (likely incorrectly!) that copy would copy the stream intact, so how can it also resize?

Learning as I go 😃 

Thanks!

**Comment by arrmo** [comment]
Hi,

@deathbybandaid do you want me to submit a PR for this (or actually, 2 - fHDHR, and ffmpeg plugin)? 100% your call of course! It is working, and the changes are pretty minor overall. I know you're working on where you want ffmpeg go to, but I think this is some what independent of that ... meaning that it just enables transcoding selection (and HW accel), wherever ffmpeg ends up at in the end. But I may be wrong, feel free to disagree! And if you want to check out the changes, separate from a PR,
https://github.com/arrmo/fHDHR/tree/hwaccel => change here is only to remove the check, let it happen in ffmpeg
https://github.com/arrmo/fHDHR_plugin_stream_ffmpeg/tree/hwaccel => takes transcode parameters from a file (transcode.json) ... defaults to the copy, as originally (if no file, or not specified), but also allows custom global, input and output ffmpeg parameters (inside the plugin of course).


@DanAustinGH, just to keep you in the loop as well.

Thanks!

**Comment by deathbybandaid** [comment]
When I have time gain, I'll look into this.

The trancode profile system should be part of core (even though core can't utilize it.) 

I would make a system that checks if a plugin has transode profiles to import, and import them.

I would move built-in profiles to the HDHR interface plugin, as those are what a real HDHR would expect.

The json for a profile would also need to indicate if it is reliant on certain plugins being installed, like ffmpeg.

**Comment by deathbybandaid** [comment]
Another thought is distinguishing profiles for nvidia/intel/amd hardware accelleration

**Comment by deathbybandaid** [comment]
I also want this to be something that core can handle for other streaming methods, like vlc

**Comment by deathbybandaid** [comment]
Doing it in core also allows me to create per-origin configuration for this. As you might want one origin to use hardware accelleration, and one to use cpu

**Comment by arrmo** [comment]
> When I have time gain, I'll look into this.

NP, thanks!

> The trancode profile system should be part of core (even though core can't utilize it.)

You definitely know better than I do where to incorporate it - no issue at all if it should be shifted somewhere else.

> I would make a system that checks if a plugin has transode profiles to import, and import them.

Sorry, trying to follow - as only ffmpeg can actually transcode, right?

> Another thought is distinguishing profiles for nvidia/intel/amd hardware accelleration

Yep, I was thinking about that - but trying to capture all combinations => I could see 10's (or more) of these. Heck, Plex applies 50 options to a single ffmpeg command => I was trying to not have fHDHR capture a long list of options ... provide a few stock ones (like you had, I included those), and let folks tweak if they want. If fHDHR tries to capture all the permutations and combinations ... well, I think that's a huge list 😞. But feel free to disagree!

> I also want this to be something that core can handle for other streaming methods, like vlc

But it has to go "through" ffmpeg to transcode, no?

> Doing it in core also allows me to create per-origin configuration for this. As you might want one origin to use hardware accelleration, and one to use cpu

Gotcha, makes sense!

**Comment by arrmo** [comment]
It may be that what I have here is just a start - no issue at all! Wanted to see if HW (or CPU) could be made to work, and to have it dynamic => don't force fHDHR to restart to try config / transcoding changes. That part is working 😄 

Thanks!

**Comment by arrmo** [comment]
And to explain - the "dynamic" part ... a restart of fHDHR is a "bad" thing - in my setup at least. LMAO!

**Comment by deathbybandaid** [comment]
VLC plugin can do profiles too.

The direct method warns that it can't transcode

**Comment by arrmo** [comment]
> VLC plugin can do profiles too.

That makes sense - I would assume that the parameters are different, but of course that can be handled in the values stored.

> The direct method warns that it can't transcode

Agreed! And @DanAustinGH pointed out somewhere along the line 😆 - direct and hardware aren't really the same thing. Hardware is about taking the input direct from /dev (not RTP/UDP), while direct vs. ffmpeg is about passing through ffmpeg (and perhaps transcoding). Agreed? BTW, it does work this way, no issues at all ... direct really just passes it through, and separately it can come from HW.

**Comment by DanAustinGH** [comment]
Thoughts in random order.  I like having the profiles in a config file to make testing/changing easier.  Having the profiles loaded in the core still makes senses for maximum flexibility.  I have had no luck using VLC on my server, so I cannot test profiles on it.  I also only have NVidia for acceleration, so I cannot test profiles for VAAPI/Quicksync/etc.

But going back to profiles in a config, it would be easier for the community to develop and contribute profiles if they did not have to restart fHDHR after every change.

**Comment by arrmo** [comment]
FYI, found this handy / interesting,
https://www.elpamsoft.com/?p=Plex-Hardware-Transcoding

**Comment by arrmo** [comment]
Hi,

I do have this working locally - and can provide a PR ... but you were thinking about how to deal with ffmpeg overall?

Thanks!

**Comment by arrmo** [comment]
Sorry, this one got auto-closed, but I still have a PR I can push if you want. It is working quite well, prime time here on a daily basis. I admit, I really like that it uses HW accel.

Thoughts?

Thanks!
